{% set name = "xcanvas" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinRenou/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6b9f1a0e5bddb6a5f63ab3991ee7e7d46509d36632c69bde83c0fb9ffbf3799b

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xeus-zmq >=1.0.1,<2.0
    - xtl >=0.7.0,<0.8
    - xproperty >=0.11.0,<0.12
    - xwidgets >=0.27.0,<0.28
  run:
    - ipycanvas >=0.11.0,<0.12

test:
  commands:
    - test -d ${PREFIX}/include/xcanvas  # [unix]
    - test -f ${PREFIX}/include/xcanvas/xcanvas.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xcanvas/xcanvasConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xcanvas/xcanvasConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xcanvas\xcanvas.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xcanvasConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xcanvasConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/martinRenou/xcanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ back-end for ipycanvas'
  dev_url: https://github.com/martinRenou/xcanvas

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
